"""Career Intelligence PDF reports (ReportLab, A4, MicroDegree / MyCareer AI branding)."""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from functools import partial
from io import BytesIO
from typing import Any
from xml.sax.saxutils import escape

import qrcode
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.resume_analysis import ContactBasics, ResumeAnalysisOutput
from app.services.recommendation_engine import enrich_resume_analysis_with_microdegree_paths

COMPANY_LINE = "MyCareer AI"
SUBTITLE = "Career Intelligence Report"
POWERED_BY = "Powered by MicroDegree"
FOOTER_TAGLINE = "Generated by MyCareer AI powered by MicroDegree"
CONFIDENTIAL_TAGLINE = "Confidential — for the candidate and authorized reviewers only"

# MicroDegree palette (spec)
BRAND_NAVY = colors.HexColor("#1E3A8A")
BRAND_ACCENT = colors.HexColor("#0369A1")
BRAND_PANEL = colors.HexColor("#EFF6FF")
BRAND_RULE = colors.HexColor("#1E3A8A")
BRAND_DARK = colors.HexColor("#0f172a")
BRAND_MUTED = colors.HexColor("#64748b")
BRAND_GRID = colors.HexColor("#E2E8F0")

# Content budgets (A4; slightly more room than legacy Letter layout)
_SUMMARY_MAX = 900
_SKILLS_TECH_MAX = 16
_PROF_MAX = 400
_ATS_NOTES_MAX = 320
_ATS_BULLETS = 8
_CAREER_ROLES = 10
_OUTLOOK_MAX = 420
_IMPROVE_BULLETS = 8
_GAP_ITEMS = 8
_INDUSTRY_CTX_MAX = 320
_COURSES = 8
_SW_QUICK = 8


def clean_text(text: str | None) -> str:
    """Strip HTML-like tags and normalize whitespace for safe PDF text."""
    if not text:
        return ""
    s = re.sub(r"<[^>]+>", "", str(text))
    s = s.replace("&nbsp;", " ").replace("\xa0", " ")
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _safe_findings_dict(raw: Any) -> dict[str, Any] | None:
    if raw is None:
        return None
    if isinstance(raw, dict):
        return dict(raw)
    if isinstance(raw, str):
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return None
    return None


def _parse_analysis_output(findings: dict[str, Any] | None) -> ResumeAnalysisOutput | None:
    if not findings:
        return None
    data = {k: v for k, v in findings.items() if k != "_meta"}
    try:
        nlp = ResumeAnalysisOutput.model_validate(data)
        return enrich_resume_analysis_with_microdegree_paths(nlp)
    except Exception:
        return None


def _plain(text: str | None, style: ParagraphStyle) -> Paragraph:
    return Paragraph(escape(clean_text(text)), style)


def _bullets(items: list[str], style: ParagraphStyle, max_items: int) -> list:
    out: list = []
    slice_ = items[:max_items]
    for it in slice_:
        t = clean_text(str(it))
        if t:
            out.append(Paragraph(f"• {escape(t)}", style))
            out.append(Spacer(1, 3))
    if len(items) > max_items:
        out.append(
            Paragraph(
                f"<i>{escape(f'…and {len(items) - max_items} more in the app')}</i>",
                style,
            )
        )
    return out


def _skill_gap_flowables(
    nlp: ResumeAnalysisOutput | None,
    bullet_style: ParagraphStyle,
    body_style: ParagraphStyle,
) -> list:
    out: list = []
    if nlp and nlp.skill_gap_analysis.gaps:
        for g in nlp.skill_gap_analysis.gaps[:_GAP_ITEMS]:
            sk = clean_text(g.skill)
            imp = clean_text(g.importance)
            desc = clean_text(g.gap_description[:280])
            line = f"<b>{escape(sk)}</b> ({escape(imp)}): {escape(desc)}"
            out.append(Paragraph(line, bullet_style))
            out.append(Spacer(1, 3))
        ctx = clean_text(nlp.skill_gap_analysis.industry_context)
        if ctx:
            out.append(_plain(ctx[:_INDUSTRY_CTX_MAX], body_style))
        return out

    if not nlp:
        out.append(
            _plain(
                "Structured skill gap data was not available for this export. "
                "Re-run resume analysis in MyCareer AI for a detailed gap map.",
                body_style,
            )
        )
        return out

    parts: list[str] = []
    if nlp.weaknesses:
        w_join = "; ".join(clean_text(w) for w in nlp.weaknesses[:6] if clean_text(w))
        if w_join:
            parts.append("Focus areas (from your analysis): " + w_join)
    if nlp.improvement_suggestions:
        s_join = "; ".join(
            clean_text(s) for s in nlp.improvement_suggestions[:5] if clean_text(s)
        )
        if s_join:
            parts.append("Resume improvements to close common gaps: " + s_join)
    pn = clean_text(nlp.skills_assessment.proficiency_notes)
    if pn:
        parts.append(pn[:400])
    if nlp.recommended_roles:
        r_join = ", ".join(clean_text(r) for r in nlp.recommended_roles[:5] if clean_text(r))
        if r_join:
            parts.append(
                "Skills implied by target roles ("
                + r_join
                + "): prioritize depth in the stack you use most, plus measurable outcomes."
            )
    if nlp.ats_compatibility.suggestions:
        a_join = "; ".join(
            clean_text(s) for s in nlp.ats_compatibility.suggestions[:4] if clean_text(s)
        )
        if a_join:
            parts.append(
                "ATS-oriented improvements that often correlate with clearer skill signaling: "
                + a_join
            )

    if parts:
        out.append(_plain(" ".join(parts)[:1600], body_style))
    else:
        out.append(
            _plain(
                "No dedicated skill-gap rows were stored. Use the in-app analysis to "
                "prioritize skills against your target roles and refresh this report.",
                body_style,
            )
        )
    return out


def _qr_block(url: str | None, caption_style: ParagraphStyle) -> list:
    if not url or not str(url).strip():
        return []
    try:
        buf = BytesIO()
        qr = qrcode.QRCode(version=None, box_size=2, border=1)
        qr.add_data(url.strip())
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        img.save(buf, format="PNG")
        buf.seek(0)
        im = Image(ImageReader(buf), width=0.72 * inch, height=0.72 * inch)
        return [
            im,
            Spacer(1, 4),
            _plain("Scan to open this analysis in the app", caption_style),
        ]
    except Exception:
        return []


def _display_or_dash(v: str | None) -> str:
    t = clean_text(v)
    return t if t else "Not provided"


def _merge_contact(
    nlp: ResumeAnalysisOutput | None,
    *,
    candidate_display_name: str | None,
    candidate_email: str | None,
    candidate_phone: str | None,
    candidate_linkedin_url: str | None,
    candidate_github_url: str | None,
) -> tuple[str, str, str, str, str]:
    """Prefer explicit profile fields; fall back to resume-extracted basics."""
    basics: ContactBasics | None = None
    if nlp and nlp.structured_resume and nlp.structured_resume.basics:
        basics = nlp.structured_resume.basics

    def pick(explicit: str | None, attr: str) -> str:
        e = clean_text(explicit)
        if e:
            return e
        if basics is not None:
            return _display_or_dash(getattr(basics, attr, None))
        return "Not provided"

    name = pick(candidate_display_name, "name")
    email = pick(candidate_email, "email")
    phone = pick(candidate_phone, "phone")
    linkedin = pick(candidate_linkedin_url, "linkedin")
    github = pick(candidate_github_url, "github")
    return name, email, phone, linkedin, github


def _candidate_table(
    name: str,
    email: str,
    phone: str,
    linkedin: str,
    github: str,
    label_style: ParagraphStyle,
    value_style: ParagraphStyle,
) -> Table:
    def lbl(t: str) -> Paragraph:
        return Paragraph(f"<b>{escape(t)}</b>", label_style)

    def val(t: str) -> Paragraph:
        return Paragraph(escape(_display_or_dash(t)), value_style)

    data = [
        [lbl("Full name"), val(name), lbl("Email"), val(email)],
        [lbl("Phone"), val(phone), lbl("LinkedIn"), val(linkedin)],
        [lbl("GitHub"), val(github), "", ""],
    ]
    tbl = Table(data, colWidths=[1.0 * inch, 2.2 * inch, 1.0 * inch, 2.2 * inch])
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                ("BOX", (0, 0), (-1, -1), 0.75, BRAND_NAVY),
                ("INNERGRID", (0, 0), (-1, -1), 0.35, BRAND_GRID),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("SPAN", (1, 2), (3, 2)),
            ]
        )
    )
    return tbl


def _score_pair_table(
    resume_score: int,
    ats_score: int,
    card_title_style: ParagraphStyle,
    *,
    col_a: float,
    col_b: float,
) -> Table:
    """Two side-by-side metric cells; column widths must fit the parent layout."""
    # One Paragraph per cell so Table can pass avail width (KeepTogether stacks broke wrapping).
    left = Paragraph(
        f"<b>{escape('Resume score')}</b><br/><br/>"
        f"<font face='Helvetica-Bold' size='28' color='#1E3A8A'>{resume_score}</font>"
        f"<font size='11' color='#64748b'> /100</font>",
        card_title_style,
    )
    right = Paragraph(
        f"<b>{escape('ATS compatibility')}</b><br/><br/>"
        f"<font face='Helvetica-Bold' size='28' color='#1E3A8A'>{ats_score}</font>"
        f"<font size='11' color='#64748b'> /100</font>",
        card_title_style,
    )
    inner = Table(
        [[left, right]],
        colWidths=[col_a, col_b],
    )
    inner.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), BRAND_PANEL),
                ("BOX", (0, 0), (-1, -1), 0.75, BRAND_ACCENT),
                ("LINEAFTER", (0, 0), (0, -1), 0.5, BRAND_GRID),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ]
        )
    )
    return inner


def _on_page(canvas: Any, doc: SimpleDocTemplate, *, report_id: str, generated_at: datetime) -> None:
    canvas.saveState()
    w, h = A4
    # Thin top rule (brand)
    canvas.setStrokeColor(BRAND_RULE)
    canvas.setLineWidth(1.25)
    y_top = h - 0.45 * inch
    canvas.line(0.6 * inch, y_top, w - 0.6 * inch, y_top)

    canvas.setFillColor(BRAND_NAVY)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(0.6 * inch, h - 0.38 * inch, COMPANY_LINE)

    canvas.setFillColor(BRAND_MUTED)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(w - 0.6 * inch, h - 0.38 * inch, SUBTITLE)

    # Footer
    ts = generated_at.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")
    foot_main = f"{FOOTER_TAGLINE}  ·  Report ID: {report_id}  ·  {ts}"
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(BRAND_MUTED)
    canvas.drawCentredString(w / 2, 0.45 * inch, foot_main)
    pg = canvas.getPageNumber()
    canvas.drawCentredString(w / 2, 0.32 * inch, f"Page {pg}")

    canvas.restoreState()


def build_analysis_pdf_bytes(
    *,
    analysis_id: str,
    summary_column: str,
    findings_raw: Any,
    scores_raw: Any,
    analysis_version: int,
    model_name: str | None = None,
    candidate_display_name: str | None = None,
    candidate_email: str | None = None,
    candidate_phone: str | None = None,
    candidate_linkedin_url: str | None = None,
    candidate_github_url: str | None = None,
    online_report_url: str | None = None,
) -> bytes:
    findings = _safe_findings_dict(findings_raw)
    scores = _safe_findings_dict(scores_raw) or {}
    nlp = _parse_analysis_output(findings)

    resume_score = int(scores.get("resume_score", 0) or 0)
    if nlp is not None:
        resume_score = nlp.resume_score

    ats_score = int(scores.get("ats_score", 0) or 0)
    if nlp:
        ats_score = nlp.ats_compatibility.score

    c_name, c_email, c_phone, c_li, c_gh = _merge_contact(
        nlp,
        candidate_display_name=candidate_display_name,
        candidate_email=candidate_email,
        candidate_phone=candidate_phone,
        candidate_linkedin_url=candidate_linkedin_url,
        candidate_github_url=candidate_github_url,
    )

    generated_at = datetime.now(UTC)
    report_id = clean_text(analysis_id) or "—"

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=1.05 * inch,
        bottomMargin=0.75 * inch,
        title=f"{COMPANY_LINE} — {SUBTITLE}",
    )

    styles = getSampleStyleSheet()
    doc_title = ParagraphStyle(
        name="MD_DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=BRAND_NAVY,
        spaceAfter=4,
        leading=24,
        alignment=TA_LEFT,
    )
    doc_sub = ParagraphStyle(
        name="MD_DocSub",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        textColor=BRAND_ACCENT,
        spaceAfter=6,
        leading=14,
    )
    micro_tag = ParagraphStyle(
        name="MD_MicroTag",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        textColor=BRAND_MUTED,
        spaceAfter=14,
        leading=11,
    )
    rule_spacer_after = Spacer(1, 0.12 * inch)

    h2_style = ParagraphStyle(
        name="MD_H2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11.5,
        textColor=BRAND_NAVY,
        spaceBefore=14,
        spaceAfter=8,
        leading=14,
        borderPadding=0,
    )
    h3_style = ParagraphStyle(
        name="MD_H3",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        textColor=BRAND_DARK,
        spaceBefore=6,
        spaceAfter=4,
        leading=12,
    )
    body_style = ParagraphStyle(
        name="MD_Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        textColor=BRAND_DARK,
        alignment=TA_JUSTIFY,
        leading=12.5,
        spaceAfter=5,
    )
    bullet_wrap = ParagraphStyle(
        name="MD_Bullet",
        parent=body_style,
        leftIndent=12,
        bulletIndent=4,
        alignment=TA_LEFT,
        fontSize=9,
        leading=12,
    )
    label_cell = ParagraphStyle(
        name="MD_LabelCell",
        parent=body_style,
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=BRAND_NAVY,
    )
    value_cell = ParagraphStyle(
        name="MD_ValueCell",
        parent=body_style,
        fontSize=9,
        leading=11,
        alignment=TA_LEFT,
        textColor=BRAND_DARK,
    )
    caption_small = ParagraphStyle(
        name="MD_Caption",
        parent=styles["Normal"],
        fontSize=7.5,
        textColor=BRAND_MUTED,
        alignment=TA_CENTER,
        leading=10,
    )
    card_title = ParagraphStyle(
        name="MD_CardTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=BRAND_NAVY,
        alignment=TA_CENTER,
        leading=14,
    )

    story: list = []

    # Header (in-flow)
    story.append(
        Paragraph(
            escape(f"{COMPANY_LINE} – {SUBTITLE}"),
            doc_title,
        )
    )
    story.append(Paragraph(f"<i>{escape(POWERED_BY)}</i>", doc_sub))
    story.append(_plain(CONFIDENTIAL_TAGLINE, micro_tag))

    # Thin blue divider (in-flow)
    line_tbl = Table([[""]], colWidths=[6.7 * inch], rowHeights=[2])
    line_tbl.setStyle(
        TableStyle(
            [
                ("LINEABOVE", (0, 0), (-1, -1), 2, BRAND_NAVY),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(line_tbl)
    story.append(rule_spacer_after)

    story.append(Paragraph(escape("Candidate information"), h2_style))
    story.append(
        _candidate_table(c_name, c_email, c_phone, c_li, c_gh, label_cell, value_cell)
    )
    story.append(Spacer(1, 0.14 * inch))

    story.append(Paragraph(escape("Key metrics"), h2_style))
    qr_bits = _qr_block(online_report_url, caption_small)
    if qr_bits:
        scores_tbl = _score_pair_table(
            resume_score,
            ats_score,
            card_title,
            col_a=2.175 * inch,
            col_b=2.175 * inch,
        )
        score_row = Table(
            [[scores_tbl, KeepTogether(qr_bits)]],
            colWidths=[4.35 * inch, 1.75 * inch],
        )
        score_row.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ALIGN", (1, 0), (1, -1), "CENTER"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        story.append(score_row)
    else:
        story.append(
            _score_pair_table(
                resume_score,
                ats_score,
                card_title,
                col_a=3.05 * inch,
                col_b=3.05 * inch,
            )
        )

    story.append(Spacer(1, 0.06 * inch))
    meta_bits = [f"Analysis version {analysis_version}"]
    if model_name and clean_text(model_name):
        meta_bits.append(f"Model {clean_text(model_name)}")
    story.append(_plain(" · ".join(meta_bits), micro_tag))

    # Executive summary
    story.append(Paragraph(escape("Executive summary"), h2_style))
    summary_text = (
        clean_text(nlp.professional_summary)
        if nlp
        else clean_text(summary_column or "")
    )
    if summary_text:
        story.append(_plain(summary_text[:_SUMMARY_MAX], body_style))
    else:
        story.append(_plain("No summary available for this analysis record.", body_style))

    # Skills analysis
    story.append(Paragraph(escape("Skills analysis"), h2_style))
    if nlp:
        sa = nlp.skills_assessment
        tech = ", ".join(clean_text(x) for x in sa.technical_skills[:_SKILLS_TECH_MAX] if clean_text(x))
        soft = ", ".join(clean_text(x) for x in sa.soft_skills[:18] if clean_text(x))
        story.append(
            Paragraph(
                f"<b>{escape('Technical skills')}</b><br/>{escape(tech or '—')}",
                body_style,
            )
        )
        story.append(Spacer(1, 4))
        story.append(
            Paragraph(
                f"<b>{escape('Soft skills')}</b><br/>{escape(soft or '—')}",
                body_style,
            )
        )
        pn = clean_text(sa.proficiency_notes)
        if pn:
            story.append(Spacer(1, 4))
            story.append(_plain(pn[:_PROF_MAX], body_style))
    else:
        story.append(
            _plain(
                "Structured skills assessment not available; re-run resume analysis.",
                body_style,
            )
        )

    # ATS compatibility
    story.append(Paragraph(escape("ATS compatibility"), h2_style))
    if nlp:
        ac = nlp.ats_compatibility
        fn = clean_text(ac.formatting_notes)
        if fn:
            story.append(_plain(fn[:_ATS_NOTES_MAX], body_style))
        if ac.suggestions:
            story.append(Paragraph(escape("Suggestions"), h3_style))
            story.extend(_bullets([clean_text(s) for s in ac.suggestions], bullet_wrap, _ATS_BULLETS))
    else:
        story.append(_plain("—", body_style))

    # Career recommendations
    story.append(Paragraph(escape("Career recommendations"), h2_style))
    if nlp:
        if nlp.recommended_roles:
            story.append(Paragraph(escape("Suitable roles"), h3_style))
            story.extend(
                _bullets([clean_text(r) for r in nlp.recommended_roles], bullet_wrap, _CAREER_ROLES)
            )
        co = clean_text(nlp.career_outlook)
        if co:
            story.append(Paragraph(escape("Outlook (5–10 years)"), h3_style))
            story.append(_plain(co[:_OUTLOOK_MAX], body_style))
        if nlp.improvement_suggestions:
            story.append(Paragraph(escape("Resume improvements"), h3_style))
            story.extend(
                _bullets(
                    [clean_text(s) for s in nlp.improvement_suggestions],
                    bullet_wrap,
                    _IMPROVE_BULLETS,
                )
            )
    else:
        story.append(_plain("—", body_style))

    # Skill gap analysis
    story.append(Paragraph(escape("Skill gap analysis"), h2_style))
    story.extend(_skill_gap_flowables(nlp, bullet_wrap, body_style))

    # Learning roadmap
    story.append(Paragraph(escape("Learning roadmap"), h2_style))
    if nlp and nlp.course_recommendations:
        for c in nlp.course_recommendations[:_COURSES]:
            title = clean_text(c.title) or "Course"
            prov = clean_text(c.provider) if c.provider else ""
            rat = clean_text(c.rationale)[:220]
            prov_bit = f" — {escape(prov)}" if prov else ""
            line = f"<b>{escape(title)}</b>{prov_bit}<br/><i>{escape(rat)}</i>"
            story.append(Paragraph(line, body_style))
            story.append(Spacer(1, 6))
    else:
        story.append(_plain("—", body_style))

    # Strengths & areas for improvement
    if nlp and (nlp.strengths or nlp.weaknesses):
        story.append(Paragraph(escape("Strengths & areas for improvement"), h2_style))
        if nlp.strengths:
            story.append(Paragraph(escape("Strengths"), h3_style))
            story.extend(_bullets([clean_text(s) for s in nlp.strengths], bullet_wrap, _SW_QUICK))
        if nlp.weaknesses:
            story.append(Paragraph(escape("Areas for improvement"), h3_style))
            story.extend(_bullets([clean_text(s) for s in nlp.weaknesses], bullet_wrap, _SW_QUICK))

    on_page = partial(_on_page, report_id=report_id, generated_at=generated_at)
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    pdf = buf.getvalue()
    buf.close()
    return pdf
