from app.prompts.career import (
    CAREER_CHAT_SYSTEM,
    RESUME_SUMMARY_SYSTEM,
)
from app.prompts.resume_analysis import (
    RESUME_ANALYSIS_SYSTEM,
    RESUME_ANALYSIS_USER_PREFIX,
    RESUME_ANALYSIS_USER_SUFFIX,
)
from app.prompts.mentor import (
    CAREER_MENTOR_BASE,
    CAREER_MENTOR_RETRIEVAL_WRAPPER,
    CAREER_MENTOR_STRUCTURED_SUFFIX,
    SYSTEM_PROMPT,
)

__all__ = [
    "RESUME_SUMMARY_SYSTEM",
    "CAREER_CHAT_SYSTEM",
    "RESUME_ANALYSIS_SYSTEM",
    "RESUME_ANALYSIS_USER_PREFIX",
    "RESUME_ANALYSIS_USER_SUFFIX",
    "CAREER_MENTOR_BASE",
    "SYSTEM_PROMPT",
    "CAREER_MENTOR_RETRIEVAL_WRAPPER",
    "CAREER_MENTOR_STRUCTURED_SUFFIX",
]
